# Generated by Django 3.0.7 on 2020-06-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(max_length=20)),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
    ]
