# Generated by Django 3.0.7 on 2020-06-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(default='student name', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now=True),
        ),
    ]
