# Generated by Django 3.0.7 on 2020-06-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200614_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='roll_number',
            field=models.IntegerField(default=0),
        ),
    ]
